# SPDX-License-Identifier: AGPL-3.0-or-later
include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-mwan4
PKG_VERSION:=0.1.0
PKG_RELEASE:=1
PKG_LICENSE:=AGPL-3.0-or-later
LUCI_TITLE:=MultiWAN 4 management (fw4)
LUCI_DEPENDS:=+luci-base +mwan4
LUCI_PKGARCH:=all
LUCI_MINIFY_JS:=0

include $(TOPDIR)/feeds/luci/luci.mk
